version: '3.4'

services:
  echo_http:
    container_name: echo_http
    build:
      context: .
      args:
        BUILD_VER: dev-build

    restart: always
    ports:
    - 127.0.0.1:8000:8000
    - 127.0.0.1:8443:8443