---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: echo

replicas:
  - name: echo
    count: 1

resources:
  - ./ns.yaml
  - ./deploy.yaml
  - ./sa.yaml
  - ./svc.yaml
  - ./rbac.yaml

patchesStrategicMerge:
  - ./deploy.env.patch.yaml
