---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: echo-pod-viewer
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: echo-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: echo-pod-viewer
subjects:
  - kind: ServiceAccount
    name: echo
    namespace: default
